### ISSUE TITLE
Document task groups configuration

### ISSUE THREAD

**Issue by porn** [3stack-software/celery-cloudwatch#8]
Hey there,

so glad to find your project! Was about to fork in order to group tasks together and found that this is already implemented, just not documented;)

I believe you have your TODO somewhere, so let's make this official? One day...

For the curious ones, this is how it can be configured in version `1.1.1`:

```yaml
ccwatch:
  broker: null
  camera: celery_cloudwatch.CloudWatchCamera
  verbose: no
camera:
  frequency: 60.0
  verbose: no
cloudwatch-camera:
  dryrun: no
  namespace: celery
  task-groups:
    - tasks:
      - myapp.mytasks.taskname
      - myapp.mytasks.anothertask
      - myapp.mytasks.thirdtask
      dimensions:
        whatever: something-here
```
